fix(publish-release-candidate.yml)

diff --git a/.github/workflows/publish-release-candidate.yml b/.github/workflows/publish-release-candidate.yml
--- a/.github/workflows/publish-release-candidate.yml
+++ b/.github/workflows/publish-release-candidate.yml
@@ -1,7 +1,11 @@
+name: Publish release candidate
+
 on:
   push:
     tags:
-      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
+      # To bump, and push tagged commit:
+      #   yarn version --prerelease && git push && git push --follow-tags || echo "FAILED!"
+      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
   workflow_dispatch:
 
 jobs:
@@ -11,7 +15,7 @@ jobs:
       contents: read
       packages: write
     env:
-      APP_NAME: ds
+      APP_NAME: telicent-frontend-cli
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
@@ -46,4 +50,10 @@ jobs:
       - name: Install dependencies
         run: yarn install --frozen-lockfile
       - run: yarn build
-      - run: npm publish --tag ${{ steps.tag-name.outputs.tag }} --access public --provenance
+      - name: Get dist tag without version suffix
+        id: extract-dist-tag
+        run: |
+          # Extract the dist tag without version suffix e.g. 0.0.0-alpha.1 = alpha, 0.0.0-beta = beta
+          dist_tag=$(echo "${{ steps.tag-name.outputs.tag }}" | sed 's/\.[0-9]\+$//' | cut -d'-' -f2)
+          echo "::set-output name=dist-tag::$dist_tag" # Set the output variable
+      - run: npm publish --tag ${{ steps.extract-dist-tag.outputs.dist-tag }} --access public --provenance
